language: csharp
solution: Imgix-CSharp.sln

install:
  - msbuild /t:Restore imgix-csharp.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release imgix-csharp.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./tests/Imgix.Tests/bin/Release/net46/Imgix.Tests.dll
